task: 'zju_mocap'
subject: 'xiao'
experiment: 'train-all'

##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'pjlab_xiao_view0235_500-800'
  selected_frame: all

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'pjlab_xiao_view0235_500-800'

train_render:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'pjlab_xiao_view0235_500-800'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'pjlab_xiao_view0235_500-800'

novelview:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'pjlab_xiao_view14_500-800_step5'

novelpose_eval:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'pjlab_xiao_view14_after-800_step4'


bgcolor: [0., 0., 0.]
resize_img_scale: 1.0
