task: 'zju_mocap'
subject: 'xiao'
experiment: 'train-all'

##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'pjlab_xiao_train-all_view00'
  selected_frame: all

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'pjlab_xiao_train-all_view00'


bgcolor: [0., 0., 0.]
resize_img_scale: 1.0
