task: 'zju_mocap'
subject: 'p387'
experiment: 'tava_split'

##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_387_tava_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_387_tava_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_387_tava_test_1view'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'zju_387_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'zju_387_test'

novelpose:
  dataset_module: 'core.data.human_nerf.novelpose'
  dataset: 'zju_387_test'

novelview:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_387_test_fr-tv_vw-3-9-15-22'

novelview_all:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_387_test_fr-tv_vw-all'

novelpose_eval:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_387_test_fr-tv_vw-3-9-15-22_ood'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.5
